# Generated by Django 3.0.8 on 2020-08-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20200807_1852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='starting_bid',
            new_name='bid',
        ),
        migrations.AddField(
            model_name='bid',
            name='user',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
